*&---------------------------------------------------------------------*
*& Report ZB014_ADDPEOPLE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZB014_ADDPEOPLE.

TYPES: BEGIN OF PEOPLE_BIRTHDAYS_STRUCT,
         MANDT        TYPE SY-MANDT,
         ID           TYPE ZB014_BIRTHDAYS-FRIEND_NUMBER,
         FIRSTNAME    TYPE ZB014_BIRTHDAYS-FRIEND_FIRSTNAME,
         LASTNAME     TYPE ZB014_BIRTHDAYS-FRIEND_LASTNAME,
         DAYOFBIRTH   TYPE ZB014_BIRTHDAYS-DAY_OF_BIRTH,
         MONTHOFBIRTH TYPE ZB014_BIRTHDAYS-MONTH_OF_BIRTH,
         YEAROFBIRTH  TYPE ZB014_BIRTHDAYS-YEAR_OF_BIRTH,
       END OF PEOPLE_BIRTHDAYS_STRUCT.

TYPES: BIRTHDAYSTABLETYPE TYPE SORTED TABLE OF PEOPLE_BIRTHDAYS_STRUCT WITH UNIQUE KEY ID.

DATA: ITABLE TYPE BIRTHDAYSTABLETYPE.

DATA: PERSON TYPE PEOPLE_BIRTHDAYS_STRUCT.

*ADD PEOPLE TO TABLE

PERSON-ID = 1003.
PERSON-FIRSTNAME = 'Jeremy'.
PERSON-LASTNAME = 'Lewis'.
PERSON-DAYOFBIRTH = 13.
PERSON-MONTHOFBIRTH = 'JAN'.
PERSON-YEAROFBIRTH = 1988.
INSERT PERSON INTO TABLE ITABLE.


PERSON-ID = 2941.
PERSON-FIRSTNAME = 'Michelle'.
PERSON-LASTNAME = 'Davis'.
PERSON-DAYOFBIRTH = 29.
PERSON-MONTHOFBIRTH = 'JUN'.
PERSON-YEAROFBIRTH = 1998.
INSERT PERSON INTO TABLE ITABLE.

PERSON-ID = 9512.
PERSON-FIRSTNAME = 'Michael'.
PERSON-LASTNAME = 'Wellington'.
PERSON-DAYOFBIRTH = 21.
PERSON-MONTHOFBIRTH = 'NOV'.
PERSON-YEAROFBIRTH = 2001.
INSERT PERSON INTO TABLE ITABLE.

PERSON-ID = 6666.
PERSON-FIRSTNAME = 'Kenneth'.
PERSON-LASTNAME = 'McCormick'.
PERSON-DAYOFBIRTH = 13.
PERSON-MONTHOFBIRTH = 'AUG'.
PERSON-YEAROFBIRTH = 1997.
INSERT PERSON INTO TABLE ITABLE.

INSERT ZB014_BIRTHDAYS FROM TABLE ITABLE ACCEPTING DUPLICATE KEYS.

WRITE SY-DBCNT.
WRITE: 'records updated'.
