*&---------------------------------------------------------------------*
*& Report ZB014_LIBRARY
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZB014_LIBRARY.
TYPES: BEGIN OF BOOK_TYPE,
         BOOK_TITLE       TYPE C LENGTH 200,
         PRIMARY_AUTHOR   TYPE C LENGTH 100,
         PUBLISHER        TYPE C LENGTH 100,
         PUBLISHER_STATE  TYPE C LENGTH 2,
         PUBLICATION_DATE TYPE D,
         TRACKING_ID      TYPE N LENGTH 9,
         PURCHASE_COST    TYPE P DECIMALS 2,
         DATE_OF_PURCHASE TYPE D,
       END OF BOOK_TYPE.

DATA BOOK_0001 TYPE BOOK_TYPE.
BOOK_0001-BOOK_TITLE = 'HAIRY POTTER: PRISONER IN ALKATRAZ'.
BOOK_0001-PRIMARY_AUTHOR = 'VINCE K. McMAHON'.
BOOK_0001-PUBLISHER = 'PENGUIN PUBLISHING'.
BOOK_0001-PUBLISHER_STATE = 'WA'.
BOOK_0001-PUBLICATION_DATE = '19910215'.
BOOK_0001-TRACKING_ID = 770519623.
BOOK_0001-PURCHASE_COST = '15.85'.
BOOK_0001-DATE_OF_PURCHASE = '20220125'.

DATA BOOK_0002 TYPE BOOK_TYPE.
BOOK_0002-BOOK_TITLE = 'HAVING TERRIBLE CHILDREN'.
BOOK_0002-PRIMARY_AUTHOR = 'KRIS JENNER'.
BOOK_0002-PUBLISHER = 'TMZ LITERARY MEDIA OUTLET'.
BOOK_0002-PUBLISHER_STATE = 'CA'.
BOOK_0002-PUBLICATION_DATE = '20150807'.
BOOK_0002-TRACKING_ID = 770516409.
BOOK_0002-PURCHASE_COST = '12.99'.
BOOK_0002-DATE_OF_PURCHASE = '20220201'.

WRITE : 'BOOK TITLE: ', (*)BOOK_0001-BOOK_TITLE.
WRITE /.
WRITE : 'AUTHOR: ', (*)BOOK_0001-PRIMARY_AUTHOR.
WRITE /.
WRITE : 'PUBLISHER: ', (*)BOOK_0001-PUBLISHER, ', ', BOOK_0001-PUBLISHER_STATE.
WRITE /.
WRITE : 'PUBLISHED: ', BOOK_0001-PUBLICATION_DATE MM/DD/YYYY.
WRITE /.
WRITE : 'TRACKING ID: ', (*)BOOK_0001-TRACKING_ID.
WRITE /.
WRITE : 'PURCHASE COST: $', (*)BOOK_0001-PURCHASE_COST.
WRITE /.
WRITE : 'DATE OF PURCHASE: ', BOOK_0001-DATE_OF_PURCHASE MM/DD/YYYY.

WRITE /.
WRITE /.

WRITE : 'BOOK TITLE: ', (*)BOOK_0002-BOOK_TITLE.
WRITE /.
WRITE : 'AUTHOR: ', (*)BOOK_0002-PRIMARY_AUTHOR.
WRITE /.
WRITE : 'PUBLISHER: ', (*)BOOK_0002-PUBLISHER, ', ', BOOK_0001-PUBLISHER_STATE.
WRITE /.
WRITE : 'PUBLISHED: ', BOOK_0002-PUBLICATION_DATE MM/DD/YYYY.
WRITE /.
WRITE : 'TRACKING ID: ', (*)BOOK_0002-TRACKING_ID.
WRITE /.
WRITE : 'PURCHASE COST: $', (*)BOOK_0002-PURCHASE_COST.
WRITE /.
WRITE : 'DATE OF PURCHASE: ', BOOK_0002-DATE_OF_PURCHASE MM/DD/YYYY.

WRITE /.
WRITE /.

WRITE : 'TITLE','                                 ' ,'AUTHOR','                     ','PUBLISHER','                  ','STATE','           ','PUBLISHED','         ','TRACKING ID','         ','COST','          ','PURCHASED'.
WRITE /.

WRITE: (*)BOOK_0001-BOOK_TITLE UNDER 'TITLE', (*)BOOK_0001-PRIMARY_AUTHOR UNDER 'AUTHOR', (*)BOOK_0001-PUBLISHER UNDER 'PUBLISHER', BOOK_0001-PUBLISHER_STATE UNDER 'STATE',
  BOOK_0001-PUBLICATION_DATE MM/DD/YYYY UNDER 'PUBLISHED', BOOK_0001-TRACKING_ID UNDER 'TRACKING ID', '$' UNDER 'COST',(*)BOOK_0001-PURCHASE_COST UNDER 'COST',
  BOOK_0001-DATE_OF_PURCHASE MM/DD/YYYY UNDER 'PURCHASED'.

WRITE /.

WRITE: (*)BOOK_0002-BOOK_TITLE UNDER 'TITLE', (*)BOOK_0002-PRIMARY_AUTHOR UNDER 'AUTHOR', (*)BOOK_0002-PUBLISHER UNDER 'PUBLISHER' , BOOK_0002-PUBLISHER_STATE UNDER 'STATE',
  BOOK_0002-PUBLICATION_DATE MM/DD/YYYY UNDER 'PUBLISHED', BOOK_0002-TRACKING_ID UNDER 'TRACKING ID', '$' UNDER 'COST',(*)BOOK_0002-PURCHASE_COST UNDER 'COST',
  BOOK_0002-DATE_OF_PURCHASE MM/DD/YYYY UNDER 'PURCHASED'.
